#!/usr/bin/env node
// 把 src/inject/renderer-inject.js 编译成 TS 模块，让 bun --compile 能把它内联进单二进制。
// dev (tsx) 模式下也能直接 import 这个模块，避免运行时再去磁盘找 JS 文件。

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const src = resolve(here, '..', 'src', 'inject', 'renderer-inject.js')
const dst = resolve(here, '..', 'src', 'inject', 'renderer-inject.embedded.ts')

const body = await readFile(src, 'utf8')

// JSON.stringify 产出的 JSON 字符串是合法的 JS 字符串字面量，会正确 escape
// 反斜杠 / 双引号 / 换行 / Unicode 控制字符
const literal = JSON.stringify(body)

const out = `// AUTO-GENERATED by scripts/embed-inject.mjs — DO NOT EDIT
// 源文件：src/inject/renderer-inject.js
export default ${literal}
`

await writeFile(dst, out, 'utf8')
console.log(`[embed-inject] wrote ${dst} (${body.length} bytes)`)
